server:
  port: 8080
spring:
  application:
    name: consumer-app


dubbo:
  application:
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000000
    # 新加的参数
    parameters:
      blockUntilConnectedWait: 9999999
  protocol:
    name: dubbo
#    port: -1


config-app:
  file: F:\\temp\\outer-file.properties