
spring:
  application:
    name: consumer-app
server:
  port: 6060
dubbo:
  application:
    qos-enable: false
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: tri
    port: -1