server:
  port: 8080
spring:
  application:
    name: consumer-app
  servlet:
    multipart:
      max-file-size: 10MB  #每个文件大小
      max-request-size: 30MB  #请求上传文件总量


dubbo:
  application:
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000000
    # 新加的参数
    parameters:
      blockUntilConnectedWait: 9999999
  protocol:
    name: dubbo
#    port: -1


config-app:
  file: F:\\temp\\outer-file.properties

files:
  picture:
    path: D:\\temp\\picture\\
    source-path: source
    small-path: small
    url-prefix: http://localhost//