server:
  port: 6060
spring:
  application:
    name: consumer-app


dubbo:
  application:
    qos-enable: false
  registry:
    address: zookeeper://47.94.159.35:2181
    timeout: 5000000
    # 新加的参数
    parameters:
      blockUntilConnectedWait: 9999999
  protocol:
    name: dubbo
#    port: -1